import { toObjectId } from "../../../lib";
import { DATABASE } from "../../../constants";

const table = [
    { name: "MAIN_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 7, account_name: "", account_number: "2015162861", account_type: "CORPORATE", usage: "REGULAR", category: "INCOME", description: "Consist of bulk deposits from all PMT depot" },
    { name: "MANAGEMENT_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 7, account_name: "", account_number: "2015185464", account_type: "CORPORATE", usage: "REGULAR", category: "EXPENSES", description: "For all administrative expenses raised by cheque" },
    { name: "POS_MAIN_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 17, account_name: "", account_number: "1010217718", account_type: "CORPORATE", usage: "REGULAR", category: "INCOME", description: "Collation of all remittance Acc" },
    { name: "PEACE_CLEARING_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 7, account_name: "", account_number: "2022900607", account_type: "CORPORATE", usage: "REGULAR", category: "BOTH", description: "Import-Export Acc" },
    { name: "SCRAP_SALES_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 3, account_name: "", account_number: "0373016993", account_type: "CORPORATE", usage: "REGULAR", category: "INCOME", description: "Sales of Scrap Acc" },
    { name: "VEHICLE_SALES_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 3, account_name: "", account_number: "0373007838", account_type: "CORPORATE", usage: "REGULAR", category: "INCOME", description: "Sales of Vehicle" },
    { name: "PEACE_MEDICAL_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 7, account_name: "", account_number: "2020085119", account_type: "CORPORATE", usage: "REGULAR", category: "BOTH", description: "Peace medical Centre" },
    { name: "MAIN_ACCOUNT", subsidiary: "PML", terminal_id: 1, bank_id: 7, account_name: "", account_number: "2015162854", account_type: "CORPORATE", usage: "REGULAR", category: "INCOME", description: "Consist of Deposits from all PML Depot" },
    { name: "MANAGEMENT_ACCOUNT", subsidiary: "PML", terminal_id: 1, bank_id: 7, account_name: "", account_number: "2015997469", account_type: "CORPORATE", usage: "REGULAR", category: "EXPENSES", description: "For all Administrative Expenses raised by cheque" },
    { name: "PET_ACCOUNT", subsidiary: "PET", terminal_id: 1, bank_id: 14, account_name: "", account_number: "", account_type: "CORPORATE", usage: "REGULAR", category: "BOTH", description: "Peace Petroleum Income &Expenses Acc" },
    { name: "LUBE_ACCOUNT", subsidiary: "PET", terminal_id: 1, bank_id: 7, account_name: "", account_number: "2020085274", account_type: "CORPORATE", usage: "REGULAR", category: "BOTH", description: "Engine Oil Income-Expenses Acc." },
    { name: "UGAMA_PRESS_ACCOUNT", subsidiary: "PRESS", terminal_id: 1, bank_id: 12, account_name: "", account_number: "", account_type: "CORPORATE", usage: "REGULAR", category: "BOTH", description: "Income Expenses of Ugama Press" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 39, bank_id: 17, account_name: "PORT HARCOURT", account_number: "113007304", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 43, bank_id: 17, account_name: "OBOLLO AFOR", account_number: "113007295", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 16, bank_id: 17, account_name: "ENUGU EZIKE", account_number: "113007276", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 17, bank_id: 17, account_name: "GWAGWALADA", account_number: "113007278", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 11, bank_id: 17, account_name: "ABAKILIKI", account_number: "113007315", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 28, bank_id: 17, account_name: "OJUELEGBA", account_number: "113007297", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 27, bank_id: 17, account_name: "MAZA-MAZA", account_number: "113007290", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 45, bank_id: 17, account_name: "9TH MILE", account_number: "113007314", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 35, bank_id: 17, account_name: "MARABA", account_number: "113007289", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 29, bank_id: 17, account_name: "DOMOROSE", account_number: "113007272", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 31, bank_id: 17, account_name: "AJEGUNLE", account_number: "113007264", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 44, bank_id: 17, account_name: "YENEGOA", account_number: "113007312", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 46, bank_id: 17, account_name: "MINNA", account_number: "113007291", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 20, bank_id: 17, account_name: "KUBWA", account_number: "113007287", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 15, bank_id: 17, account_name: "ENUGU", account_number: "113007275", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 50, bank_id: 17, account_name: "EKITI", account_number: "113007274", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 44, bank_id: 17, account_name: "BWARI", account_number: "113007270", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 12, bank_id: 17, account_name: "BENIN", account_number: "113007269", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 53, bank_id: 17, account_name: "ASABA", account_number: "113007266", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 37, bank_id: 17, account_name: "AKURE", account_number: "113007265", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 19, bank_id: 17, account_name: "ZUBA", account_number: "113007313", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 45, bank_id: 17, account_name: "KUJE", account_number: "113007288", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 54, bank_id: 17, account_name: "IKOM", account_number: "113007280", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 7, bank_id: 17, account_name: "AWKA", account_number: "113007267", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 41, bank_id: 17, account_name: "AJAH", account_number: "113007262", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 4, bank_id: 17, account_name: "UYO", account_number: "113007309", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 2, bank_id: 17, account_name: "ABA", account_number: "113007261", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 3, bank_id: 17, account_name: "UMUAHIA", account_number: "113007307", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 5, bank_id: 17, account_name: "ONITSHA", account_number: "113007298", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 43, bank_id: 17, account_name: "IKORODU", account_number: "113007282", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 8, bank_id: 17, account_name: "CALABAR", account_number: "113007271", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 10, bank_id: 17, account_name: "AFIKPO", account_number: "113007316", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 56, bank_id: 17, account_name: "SULEJA", account_number: "113007306", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 23, bank_id: 17, account_name: "OWERRI", account_number: "113007303", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 33, bank_id: 17, account_name: "OSHODI", account_number: "113007300", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 47, bank_id: 17, account_name: "NYANYA", account_number: "113007294", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 40, bank_id: 17, account_name: "NSUKKA", account_number: "113007293", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 55, bank_id: 17, account_name: "KADUNA", account_number: "113007286", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 49, bank_id: 17, account_name: "JIBOWU", account_number: "113007285", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 26, bank_id: 17, account_name: "ILORIN", account_number: "113007284", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 36, bank_id: 17, account_name: "IBAFOR", account_number: "113007283", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 38, bank_id: 17, account_name: "IBADAN", account_number: "113007279", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 14, bank_id: 17, account_name: "GARIKI", account_number: "113007277", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 34, bank_id: 17, account_name: "EJIGBO", account_number: "113007273", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 13, bank_id: 17, account_name: "ABAKPA", account_number: "113007260", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 9, bank_id: 17, account_name: "WARN I", account_number: "113007310", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 21, bank_id: 17, account_name: "UTAKO", account_number: "113007308", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 30, bank_id: 17, account_name: "ORILE", account_number: "113007299", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 51, bank_id: 17, account_name: "OJOTA", account_number: "113007296", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 48, bank_id: 17, account_name: "NNEWI", account_number: "113007292", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 52, bank_id: 17, account_name: "JOS", account_number: "113007301", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 38, bank_id: 17, account_name: "SANGO", account_number: "113007302", account_type: "CORPORATE", usage: "WEBPAY", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 2, bank_id: 7, account_name: "ABA", account_number: "2020085982", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 11, bank_id: 7, account_name: "ABAKALIKI", account_number: "2020086037", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 13, bank_id: 7, account_name: "ABAKPA", account_number: "2024650614", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 41, bank_id: 7, account_name: "AJAH", account_number: "2026440983", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 31, bank_id: 7, account_name: "AJEGUNLE", account_number: "2020086178", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 10, bank_id: 7, account_name: "AFIKPO", account_number: "2020085762", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 37, bank_id: 7, account_name: "AKURE", account_number: "2026441117", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 12, bank_id: 7, account_name: "BENIN", account_number: "2022905152", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 44, bank_id: 7, account_name: "BWARI", account_number: "2023309829", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 8, bank_id: 7, account_name: "CALABAR", account_number: "2020085968", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 29, bank_id: 7, account_name: "DEMOROSE", account_number: "2020087034", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 34, bank_id: 7, account_name: "EJIGBO", account_number: "2020085793", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 15, bank_id: 7, account_name: "ENUGU", account_number: "2020085164", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 16, bank_id: 7, account_name: "ENUGU – EZIKE", account_number: "2020085559", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 14, bank_id: 7, account_name: "GARRKI", account_number: "2026441076", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 17, bank_id: 7, account_name: "GWAGWALADA", account_number: "2020085690", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 38, bank_id: 7, account_name: "IBADAN", account_number: "2020086154", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 36, bank_id: 7, account_name: "IBAFOR", account_number: "2026441014", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 43, bank_id: 7, account_name: "IKORODU", account_number: "2020085580", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 26, bank_id: 7, account_name: "ILORIN", account_number: "2026831394", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 49, bank_id: 7, account_name: "JIBOWU", account_number: "2020085858", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 20, bank_id: 7, account_name: "KUBWA", account_number: "2020086240", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 45, bank_id: 7, account_name: "KUJE", account_number: "2020085889", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 35, bank_id: 7, account_name: "MARABA", account_number: "2020086202", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 27, bank_id: 7, account_name: "MAZA-MAZA", account_number: "2022904911", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 46, bank_id: 7, account_name: "MINNA", account_number: "2020086192", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 48, bank_id: 7, account_name: "NNEWI", account_number: "2020085951", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 47, bank_id: 7, account_name: "NYANYA", account_number: "2027860876", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 40, bank_id: 7, account_name: "NSUKKA", account_number: "2020085542", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 43, bank_id: 7, account_name: "OBOLLO-AFOR", account_number: "2020087137", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 28, bank_id: 7, account_name: "OJUELEGBA", account_number: "2020248819", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 5, bank_id: 7, account_name: "ONITSHA", account_number: "2020085913", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 30, bank_id: 7, account_name: "ORILE", account_number: "2020086233", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 33, bank_id: 7, account_name: "OSHODI", account_number: "2020085810", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 23, bank_id: 7, account_name: "OWERRI", account_number: "2020086893", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 39, bank_id: 7, account_name: "PORT HARCOURT", account_number: "2020086109", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 3, bank_id: 7, account_name: "UMUAHIA", account_number: "2020085731", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 21, bank_id: 7, account_name: "UTAKO", account_number: "2020085308", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 4, bank_id: 7, account_name: "UYO", account_number: "2020086264", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 44, bank_id: 7, account_name: "YENEGOA", account_number: "2020086161", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 19, bank_id: 7, account_name: "ZUBA", account_number: "2020086219", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 13, bank_id: 17, account_name: "ABAKPA", account_number: "1014505855", account_type: "CORPORATE", usage: "POS", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 17, account_name: "ENUGU HIGH WAY", account_number: "1014505824", account_type: "CORPORATE", usage: "POS", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 1, bank_id: 17, account_name: "ENUGU LOCAL ROUTE", account_number: "1014505862", account_type: "CORPORATE", usage: "POS", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PMT", terminal_id: 14, bank_id: 17, account_name: "GARRKI", account_number: "1014505848", account_type: "CORPORATE", usage: "POS", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 2, bank_id: 7, account_name: "ABA", account_number: "2022905729", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 1, bank_id: 7, account_name: "ABAKALIKI", account_number: "2022905688", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 13, bank_id: 7, account_name: "ABAKPA", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 41, bank_id: 7, account_name: "AJAH", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 31, bank_id: 7, account_name: "AJEGUNLE", account_number: "2022905475", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 10, bank_id: 7, account_name: "AFIKPO", account_number: "2022905516", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 37, bank_id: 7, account_name: "AKURE", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 12, bank_id: 7, account_name: "BENIN", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 44, bank_id: 7, account_name: "BWARI", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 8, bank_id: 7, account_name: "CALABAR", account_number: "2022906197", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 29, bank_id: 7, account_name: "DEMOROSE", account_number: "2022905248", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 34, bank_id: 7, account_name: "EJIGBO", account_number: "202290231", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 15, bank_id: 7, account_name: "ENUGU", account_number: "2022906733", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 16, bank_id: 7, account_name: "ENUGU – EZIKE", account_number: "2022920137", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 14, bank_id: 7, account_name: "GARRKI", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 17, bank_id: 7, account_name: "GWAGWALADA", account_number: "2022905255", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 38, bank_id: 7, account_name: "IBADAN", account_number: "2022905262", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 36, bank_id: 7, account_name: "IBAFOR", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 43, bank_id: 7, account_name: "IKORODU", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 26, bank_id: 7, account_name: "ILORIN", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 49, bank_id: 7, account_name: "JIBOWU", account_number: "2022905190", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 20, bank_id: 7, account_name: "KUBWA", account_number: "2022906128", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 45, bank_id: 7, account_name: "KUJE", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 35, bank_id: 7, account_name: "MARABA", account_number: "2022905633", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 27, bank_id: 7, account_name: "MAZA-MAZA", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 46, bank_id: 7, account_name: "MINNA", account_number: "2022905279", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 48, bank_id: 7, account_name: "NNEWI", account_number: "2022920247", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 47, bank_id: 7, account_name: "NYANYA", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 40, bank_id: 7, account_name: "NSUKKA", account_number: "2022906795", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 43, bank_id: 7, account_name: "OBOLLO-AFOR", account_number: "2022905224", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 28, bank_id: 7, account_name: "OJUELEGBA", account_number: "2022905592", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 5, bank_id: 7, account_name: "ONITSHA", account_number: "2022905664", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 30, bank_id: 7, account_name: "ORILE", account_number: "2022906111", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 33, bank_id: 7, account_name: "OSHODI", account_number: "2022920175", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 23, bank_id: 7, account_name: "OWERRI", account_number: "2022906757", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 39, bank_id: 7, account_name: "PORT HARCOURT", account_number: "2022905767", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 3, bank_id: 7, account_name: "UMUAHIA", account_number: "2022905200", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 21, bank_id: 7, account_name: "UTAKO", account_number: "2022905183", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 4, bank_id: 7, account_name: "UYO", account_number: "", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 44, bank_id: 7, account_name: "YENEGOA", account_number: "2022905705", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
    { name: "REMITTANCE_ACCOUNT", subsidiary: "PML", terminal_id: 19, bank_id: 7, account_name: "ZUBA", account_number: "2022906070", account_type: "CORPORATE", usage: "REMITTANCE", category: "INCOME" },
];

const bankAccountBaseId = DATABASE.BASE_ID.BANK_ACCOUNT;
const terminalBaseId = DATABASE.BASE_ID.BANK;
const bankBaseId = DATABASE.BASE_ID.BANK;
const staffBaseId = DATABASE.BASE_ID.STAFF;

const result = table.map((record, index) => {
    const obj = Object.assign({}, record);
    obj._id = toObjectId(bankAccountBaseId, 1 + index);
    obj.bank_id = toObjectId(bankBaseId, record.bank_id);
    obj.terminal_id = toObjectId(terminalBaseId, record.terminal_id);
    obj.created_by = toObjectId(staffBaseId, 1);
    return obj;
});

export default result;
