import { toObjectId } from "../../../lib";
import { DATABASE } from "../../../constants";

const table = [
    { name: "Aba South", state: 1 },
    { name: "Arochukwu", state: 1 },
    { name: "Bende", state: 1 },
    { name: "Ikwuano", state: 1 },
    { name: "Isiala Ngwa North", state: 1 },
    { name: "Isiala Ngwa South", state: 1 },
    { name: "Isuikwuato", state: 1 },
    { name: "Obi Ngwa", state: 1 },
    { name: "Ohafia", state: 1 },
    { name: "Osisioma", state: 1 },
    { name: "Ugwunagbo", state: 1 },
    { name: "Ukwa East", state: 1 },
    { name: "Ukwa West", state: 1 },
    { name: "Umuahia North", state: 1 },
    { name: "Umuahia South", state: 1 },
    { name: "Umu Nneochi", state: 1 },
    { name: "Fufure", state: 2 },
    { name: "Ganye", state: 2 },
    { name: "Gayuk", state: 2 },
    { name: "Gombi", state: 2 },
    { name: "Grie", state: 2 },
    { name: "Hong", state: 2 },
    { name: "Jada", state: 2 },
    { name: "Lamurde", state: 2 },
    { name: "Madagali", state: 2 },
    { name: "Maiha", state: 2 },
    { name: "Mayo Belwa", state: 2 },
    { name: "Michika", state: 2 },
    { name: "Mubi North", state: 2 },
    { name: "Mubi South", state: 2 },
    { name: "Numan", state: 2 },
    { name: "Shelleng", state: 2 },
    { name: "Song", state: 2 },
    { name: "Toungo", state: 2 },
    { name: "Yola North", state: 2 },
    { name: "Yola South", state: 2 },
    { name: "Eastern Obolo", state: 3 },
    { name: "Eket", state: 3 },
    { name: "Esit Eket", state: 3 },
    { name: "Essien Udim", state: 3 },
    { name: "Etim Ekpo", state: 3 },
    { name: "Etinan", state: 3 },
    { name: "Ibeno", state: 3 },
    { name: "Ibesikpo Asutan", state: 3 },
    { name: "Ibiono-Ibom", state: 3 },
    { name: "Ika", state: 3 },
    { name: "Ikono", state: 3 },
    { name: "Ikot Abasi", state: 3 },
    { name: "Ikot Ekpene", state: 3 },
    { name: "Ini", state: 3 },
    { name: "Itu", state: 3 },
    { name: "Mbo", state: 3 },
    { name: "Mkpat-Enin", state: 3 },
    { name: "Nsit-Atai", state: 3 },
    { name: "Nsit-Ibom", state: 3 },
    { name: "Nsit-Ubium", state: 3 },
    { name: "Obot Akara", state: 3 },
    { name: "Okobo", state: 3 },
    { name: "Onna", state: 3 },
    { name: "Oron", state: 3 },
    { name: "Oruk Anam", state: 3 },
    { name: "Udung-Uko", state: 3 },
    { name: "Ukanafun", state: 3 },
    { name: "Uruan", state: 3 },
    { name: "Urue-Offong-Oruko", state: 3 },
    { name: "Uyo", state: 3 },
    { name: "Anambra East", state: 4 },
    { name: "Anambra West", state: 4 },
    { name: "Anaocha", state: 4 },
    { name: "Awka North", state: 4 },
    { name: "Awka South", state: 4 },
    { name: "Ayamelum", state: 4 },
    { name: "Dunukofia", state: 4 },
    { name: "Ekwusigo", state: 4 },
    { name: "Idemili North", state: 4 },
    { name: "Idemili South", state: 4 },
    { name: "Ihiala", state: 4 },
    { name: "Njikoka", state: 4 },
    { name: "Nnewi North", state: 4 },
    { name: "Nnewi South", state: 4 },
    { name: "Ogbaru", state: 4 },
    { name: "Onitsha North", state: 4 },
    { name: "Onitsha South", state: 4 },
    { name: "Orumba North", state: 4 },
    { name: "Orumba South", state: 4 },
    { name: "Oyi", state: 4 },
    { name: "Bauchi", state: 5 },
    { name: "Bogoro", state: 5 },
    { name: "Damban", state: 5 },
    { name: "Darazo", state: 5 },
    { name: "Dass", state: 5 },
    { name: "Gamawa", state: 5 },
    { name: "Ganjuwa", state: 5 },
    { name: "Giade", state: 5 },
    { name: "Itas-Gadau", state: 5 },
    { name: "Jama'are", state: 5 },
    { name: "Katagum", state: 5 },
    { name: "Kirfi", state: 5 },
    { name: "Misau", state: 5 },
    { name: "Ningi", state: 5 },
    { name: "Shira", state: 5 },
    { name: "Tafawa Balewa", state: 5 },
    { name: "Toro", state: 5 },
    { name: "Warji", state: 5 },
    { name: "Zaki", state: 5 },
    { name: "Ekeremor", state: 6 },
    { name: "Kolokuma-Opokuma", state: 6 },
    { name: "Nembe", state: 6 },
    { name: "Ogbia", state: 6 },
    { name: "Sagbama", state: 6 },
    { name: "Southern Ijaw", state: 6 },
    { name: "Yenagoa", state: 6 },
    { name: "Apa", state: 7 },
    { name: "Ado", state: 7 },
    { name: "Buruku", state: 7 },
    { name: "Gboko", state: 7 },
    { name: "Guma", state: 7 },
    { name: "Gwer East", state: 7 },
    { name: "Gwer West", state: 7 },
    { name: "Katsina-Ala", state: 7 },
    { name: "Konshisha", state: 7 },
    { name: "Kwande", state: 7 },
    { name: "Logo", state: 7 },
    { name: "Makurdi", state: 7 },
    { name: "Obi", state: 7 },
    { name: "Ogbadibo", state: 7 },
    { name: "Ohimini", state: 7 },
    { name: "Oju", state: 7 },
    { name: "Okpokwu", state: 7 },
    { name: "Oturkpo", state: 7 },
    { name: "Tarka", state: 7 },
    { name: "Ukum", state: 7 },
    { name: "Ushongo", state: 7 },
    { name: "Vandeikya", state: 7 },
    { name: "Askira-Uba", state: 8 },
    { name: "Bama", state: 8 },
    { name: "Bayo", state: 8 },
    { name: "Biu", state: 8 },
    { name: "Chibok", state: 8 },
    { name: "Damboa", state: 8 },
    { name: "Dikwa", state: 8 },
    { name: "Gubio", state: 8 },
    { name: "Guzamala", state: 8 },
    { name: "Gwoza", state: 8 },
    { name: "Hawul", state: 8 },
    { name: "Jere", state: 8 },
    { name: "Kaga", state: 8 },
    { name: "Kala-Balge", state: 8 },
    { name: "Konduga", state: 8 },
    { name: "Kukawa", state: 8 },
    { name: "Kwaya Kusar", state: 8 },
    { name: "Mafa", state: 8 },
    { name: "Magumeri", state: 8 },
    { name: "Maiduguri", state: 8 },
    { name: "Marte", state: 8 },
    { name: "Mobbar", state: 8 },
    { name: "Monguno", state: 8 },
    { name: "Ngala", state: 8 },
    { name: "Nganzai", state: 8 },
    { name: "Shani", state: 8 },
    { name: "Akamkpa", state: 9 },
    { name: "Akpabuyo", state: 9 },
    { name: "Bakassi", state: 9 },
    { name: "Bekwarra", state: 9 },
    { name: "Biase", state: 9 },
    { name: "Boki", state: 9 },
    { name: "Calabar Municipal", state: 9 },
    { name: "Calabar South", state: 9 },
    { name: "Etung", state: 9 },
    { name: "Ikom", state: 9 },
    { name: "Obanliku", state: 9 },
    { name: "Obubra", state: 9 },
    { name: "Obudu", state: 9 },
    { name: "Odukpani", state: 9 },
    { name: "Ogoja", state: 9 },
    { name: "Yakuur", state: 9 },
    { name: "Yala", state: 9 },
    { name: "Aniocha South", state: 10 },
    { name: "Bomadi", state: 10 },
    { name: "Burutu", state: 10 },
    { name: "Ethiope East", state: 10 },
    { name: "Ethiope West", state: 10 },
    { name: "Ika North East", state: 10 },
    { name: "Ika South", state: 10 },
    { name: "Isoko North", state: 10 },
    { name: "Isoko South", state: 10 },
    { name: "Ndokwa East", state: 10 },
    { name: "Ndokwa West", state: 10 },
    { name: "Okpe", state: 10 },
    { name: "Oshimili North", state: 10 },
    { name: "Oshimili South", state: 10 },
    { name: "Patani", state: 10 },
    { name: "Sapele", state: 10 },
    { name: "Udu", state: 10 },
    { name: "Ughelli North", state: 10 },
    { name: "Ughelli South", state: 10 },
    { name: "Ukwuani", state: 10 },
    { name: "Uvwie", state: 10 },
    { name: "Warri North", state: 10 },
    { name: "Warri South", state: 10 },
    { name: "Warri South West", state: 10 },
    { name: "Afikpo North", state: 11 },
    { name: "Afikpo South", state: 11 },
    { name: "Ebonyi", state: 11 },
    { name: "Ezza North", state: 11 },
    { name: "Ezza South", state: 11 },
    { name: "Ikwo", state: 11 },
    { name: "Ishielu", state: 11 },
    { name: "Ivo", state: 11 },
    { name: "Izzi", state: 11 },
    { name: "Ohaozara", state: 11 },
    { name: "Ohaukwu", state: 11 },
    { name: "Onicha", state: 11 },
    { name: "Egor", state: 12 },
    { name: "Esan Central", state: 12 },
    { name: "Esan North-East", state: 12 },
    { name: "Esan South-East", state: 12 },
    { name: "Esan West", state: 12 },
    { name: "Etsako Central", state: 12 },
    { name: "Etsako East", state: 12 },
    { name: "Etsako West", state: 12 },
    { name: "Igueben", state: 12 },
    { name: "Ikpoba Okha", state: 12 },
    { name: "Orhionmwon", state: 12 },
    { name: "Oredo", state: 12 },
    { name: "Ovia North-East", state: 12 },
    { name: "Ovia South-West", state: 12 },
    { name: "Owan East", state: 12 },
    { name: "Owan West", state: 12 },
    { name: "Uhunmwonde", state: 12 },
    { name: "Efon", state: 13 },
    { name: "Ekiti East", state: 13 },
    { name: "Ekiti South-West", state: 13 },
    { name: "Ekiti West", state: 13 },
    { name: "Emure", state: 13 },
    { name: "Gbonyin", state: 13 },
    { name: "Ido Osi", state: 13 },
    { name: "Ijero", state: 13 },
    { name: "Ikere", state: 13 },
    { name: "Ikole", state: 13 },
    { name: "Ilejemeje", state: 13 },
    { name: "Irepodun-Ifelodun", state: 13 },
    { name: "Ise-Orun", state: 13 },
    { name: "Moba", state: 13 },
    { name: "Oye", state: 13 },
    { name: "Awgu", state: 14 },
    { name: "Enugu East", state: 14 },
    { name: "Enugu North", state: 14 },
    { name: "Enugu South", state: 14 },
    { name: "Ezeagu", state: 14 },
    { name: "Igbo Etiti", state: 14 },
    { name: "Igbo Eze North", state: 14 },
    { name: "Igbo Eze South", state: 14 },
    { name: "Isi Uzo", state: 14 },
    { name: "Nkanu East", state: 14 },
    { name: "Nkanu West", state: 14 },
    { name: "Nsukka", state: 14 },
    { name: "Oji River", state: 14 },
    { name: "Udenu", state: 14 },
    { name: "Udi", state: 14 },
    { name: "Uzo Uwani", state: 14 },
    { name: "Bwari", state: 15 },
    { name: "Gwagwalada", state: 15 },
    { name: "Kuje", state: 15 },
    { name: "Kwali", state: 15 },
    { name: "Municipal Area Council", state: 15 },
    { name: "Balanga", state: 16 },
    { name: "Billiri", state: 16 },
    { name: "Dukku", state: 16 },
    { name: "Funakaye", state: 16 },
    { name: "Gombe", state: 16 },
    { name: "Kaltungo", state: 16 },
    { name: "Kwami", state: 16 },
    { name: "Nafada", state: 16 },
    { name: "Shongom", state: 16 },
    { name: "Yamaltu-Deba", state: 16 },
    { name: "Ahiazu Mbaise", state: 17 },
    { name: "Ehime Mbano", state: 17 },
    { name: "Ezinihitte", state: 17 },
    { name: "Ideato North", state: 17 },
    { name: "Ideato South", state: 17 },
    { name: "Ihitte-Uboma", state: 17 },
    { name: "Ikeduru", state: 17 },
    { name: "Isiala Mbano", state: 17 },
    { name: "Isu", state: 17 },
    { name: "Mbaitoli", state: 17 },
    { name: "Ngor Okpala", state: 17 },
    { name: "Njaba", state: 17 },
    { name: "Nkwerre", state: 17 },
    { name: "Nwangele", state: 17 },
    { name: "Obowo", state: 17 },
    { name: "Oguta", state: 17 },
    { name: "Ohaji-Egbema", state: 17 },
    { name: "Okigwe", state: 17 },
    { name: "Orlu", state: 17 },
    { name: "Orsu", state: 17 },
    { name: "Oru East", state: 17 },
    { name: "Oru West", state: 17 },
    { name: "Owerri Municipal", state: 17 },
    { name: "Owerri North", state: 17 },
    { name: "Owerri West", state: 17 },
    { name: "Onuimo", state: 17 },
    { name: "Babura", state: 18 },
    { name: "Biriniwa", state: 18 },
    { name: "Birnin Kudu", state: 18 },
    { name: "Buji", state: 18 },
    { name: "Dutse", state: 18 },
    { name: "Gagarawa", state: 18 },
    { name: "Garki", state: 18 },
    { name: "Gumel", state: 18 },
    { name: "Guri", state: 18 },
    { name: "Gwaram", state: 18 },
    { name: "Gwiwa", state: 18 },
    { name: "Hadejia", state: 18 },
    { name: "Jahun", state: 18 },
    { name: "Kafin Hausa", state: 18 },
    { name: "Kazaure", state: 18 },
    { name: "Kiri Kasama", state: 18 },
    { name: "Kiyawa", state: 18 },
    { name: "Kaugama", state: 18 },
    { name: "Maigatari", state: 18 },
    { name: "Malam Madori", state: 18 },
    { name: "Miga", state: 18 },
    { name: "Ringim", state: 18 },
    { name: "Roni", state: 18 },
    { name: "Sule Tankarkar", state: 18 },
    { name: "Taura", state: 18 },
    { name: "Yankwashi", state: 18 },
    { name: "Chikun", state: 19 },
    { name: "Giwa", state: 19 },
    { name: "Igabi", state: 19 },
    { name: "Ikara", state: 19 },
    { name: "Jaba", state: 19 },
    { name: "Jema'a", state: 19 },
    { name: "Kachia", state: 19 },
    { name: "Kaduna North", state: 19 },
    { name: "Kaduna South", state: 19 },
    { name: "Kagarko", state: 19 },
    { name: "Kajuru", state: 19 },
    { name: "Kaura", state: 19 },
    { name: "Kauru", state: 19 },
    { name: "Kubau", state: 19 },
    { name: "Kudan", state: 19 },
    { name: "Lere", state: 19 },
    { name: "Makarfi", state: 19 },
    { name: "Sabon Gari", state: 19 },
    { name: "Sanga", state: 19 },
    { name: "Soba", state: 19 },
    { name: "Zangon Kataf", state: 19 },
    { name: "Zaria", state: 19 },
    { name: "Albasu", state: 20 },
    { name: "Bagwai", state: 20 },
    { name: "Bebeji", state: 20 },
    { name: "Bichi", state: 20 },
    { name: "Bunkure", state: 20 },
    { name: "Dala", state: 20 },
    { name: "Dambatta", state: 20 },
    { name: "Dawakin Kudu", state: 20 },
    { name: "Dawakin Tofa", state: 20 },
    { name: "Doguwa", state: 20 },
    { name: "Fagge", state: 20 },
    { name: "Gabasawa", state: 20 },
    { name: "Garko", state: 20 },
    { name: "Garun Mallam", state: 20 },
    { name: "Gaya", state: 20 },
    { name: "Gezawa", state: 20 },
    { name: "Gwale", state: 20 },
    { name: "Gwarzo", state: 20 },
    { name: "Kabo", state: 20 },
    { name: "Kano Municipal", state: 20 },
    { name: "Karaye", state: 20 },
    { name: "Kibiya", state: 20 },
    { name: "Kiru", state: 20 },
    { name: "Kumbotso", state: 20 },
    { name: "Kunchi", state: 20 },
    { name: "Kura", state: 20 },
    { name: "Madobi", state: 20 },
    { name: "Makoda", state: 20 },
    { name: "Minjibir", state: 20 },
    { name: "Nasarawa", state: 20 },
    { name: "Rano", state: 20 },
    { name: "Rimin Gado", state: 20 },
    { name: "Rogo", state: 20 },
    { name: "Shanono", state: 20 },
    { name: "Sumaila", state: 20 },
    { name: "Takai", state: 20 },
    { name: "Tarauni", state: 20 },
    { name: "Tofa", state: 20 },
    { name: "Tsanyawa", state: 20 },
    { name: "Tudun Wada", state: 20 },
    { name: "Ungogo", state: 20 },
    { name: "Warawa", state: 20 },
    { name: "Wudil", state: 20 },
    { name: "Batagarawa", state: 21 },
    { name: "Batsari", state: 21 },
    { name: "Baure", state: 21 },
    { name: "Bindawa", state: 21 },
    { name: "Charanchi", state: 21 },
    { name: "Dandume", state: 21 },
    { name: "Danja", state: 21 },
    { name: "Dan Musa", state: 21 },
    { name: "Daura", state: 21 },
    { name: "Dutsi", state: 21 },
    { name: "Dutsin Ma", state: 21 },
    { name: "Faskari", state: 21 },
    { name: "Funtua", state: 21 },
    { name: "Ingawa", state: 21 },
    { name: "Jibia", state: 21 },
    { name: "Kafur", state: 21 },
    { name: "Kaita", state: 21 },
    { name: "Kankara", state: 21 },
    { name: "Kankia", state: 21 },
    { name: "Katsina", state: 21 },
    { name: "Kurfi", state: 21 },
    { name: "Kusada", state: 21 },
    { name: "Mai'Adua", state: 21 },
    { name: "Malumfashi", state: 21 },
    { name: "Mani", state: 21 },
    { name: "Mashi", state: 21 },
    { name: "Matazu", state: 21 },
    { name: "Musawa", state: 21 },
    { name: "Rimi", state: 21 },
    { name: "Sabuwa", state: 21 },
    { name: "Safana", state: 21 },
    { name: "Sandamu", state: 21 },
    { name: "Zango", state: 21 },
    { name: "Arewa Dandi", state: 22 },
    { name: "Argungu", state: 22 },
    { name: "Augie", state: 22 },
    { name: "Bagudo", state: 22 },
    { name: "Birnin Kebbi", state: 22 },
    { name: "Bunza", state: 22 },
    { name: "Dandi", state: 22 },
    { name: "Fakai", state: 22 },
    { name: "Gwandu", state: 22 },
    { name: "Jega", state: 22 },
    { name: "Kalgo", state: 22 },
    { name: "Koko-Besse", state: 22 },
    { name: "Maiyama", state: 22 },
    { name: "Ngaski", state: 22 },
    { name: "Sakaba", state: 22 },
    { name: "Shanga", state: 22 },
    { name: "Suru", state: 22 },
    { name: "Wasagu-Danko", state: 22 },
    { name: "Yauri", state: 22 },
    { name: "Zuru", state: 22 },
    { name: "Ajaokuta", state: 23 },
    { name: "Ankpa", state: 23 },
    { name: "Bassa", state: 23 },
    { name: "Dekina", state: 23 },
    { name: "Ibaji", state: 23 },
    { name: "Idah", state: 23 },
    { name: "Igalamela Odolu", state: 23 },
    { name: "Ijumu", state: 23 },
    { name: "Kabba-Bunu", state: 23 },
    { name: "Kogi", state: 23 },
    { name: "Lokoja", state: 23 },
    { name: "Mopa Muro", state: 23 },
    { name: "Ofu", state: 23 },
    { name: "Ogori-Magongo", state: 23 },
    { name: "Okehi", state: 23 },
    { name: "Okene", state: 23 },
    { name: "Olamaboro", state: 23 },
    { name: "Omala", state: 23 },
    { name: "Yagba East", state: 23 },
    { name: "Yagba West", state: 23 },
    { name: "Baruten", state: 24 },
    { name: "Edu", state: 24 },
    { name: "Ekiti", state: 24 },
    { name: "Ifelodun", state: 24 },
    { name: "Ilorin East", state: 24 },
    { name: "Ilorin South", state: 24 },
    { name: "Ilorin West", state: 24 },
    { name: "Irepodun", state: 24 },
    { name: "Isin", state: 24 },
    { name: "Kaiama", state: 24 },
    { name: "Moro", state: 24 },
    { name: "Offa", state: 24 },
    { name: "Oke Ero", state: 24 },
    { name: "Oyun", state: 24 },
    { name: "Pategi", state: 24 },
    { name: "Ajeromi-Ifelodun", state: 25 },
    { name: "Alimosho", state: 25 },
    { name: "Amuwo-Odofin", state: 25 },
    { name: "Apapa", state: 25 },
    { name: "Badagry", state: 25 },
    { name: "Epe", state: 25 },
    { name: "Eti Osa", state: 25 },
    { name: "Ibeju-Lekki", state: 25 },
    { name: "Ifako-Ijaiye", state: 25 },
    { name: "Ikeja", state: 25 },
    { name: "Ikorodu", state: 25 },
    { name: "Kosofe", state: 25 },
    { name: "Lagos Island", state: 25 },
    { name: "Lagos Mainland", state: 25 },
    { name: "Mushin", state: 25 },
    { name: "Ojo", state: 25 },
    { name: "Oshodi-Isolo", state: 25 },
    { name: "Shomolu", state: 25 },
    { name: "Surulere", state: 25 },
    { name: "Awe", state: 26 },
    { name: "Doma", state: 26 },
    { name: "Karu", state: 26 },
    { name: "Keana", state: 26 },
    { name: "Keffi", state: 26 },
    { name: "Kokona", state: 26 },
    { name: "Lafia", state: 26 },
    { name: "Nasarawa", state: 26 },
    { name: "Nasarawa Egon", state: 26 },
    { name: "Obi", state: 26 },
    { name: "Toto", state: 26 },
    { name: "Wamba", state: 26 },
    { name: "Agwara", state: 27 },
    { name: "Bida", state: 27 },
    { name: "Borgu", state: 27 },
    { name: "Bosso", state: 27 },
    { name: "Chanchaga", state: 27 },
    { name: "Edati", state: 27 },
    { name: "Gbako", state: 27 },
    { name: "Gurara", state: 27 },
    { name: "Katcha", state: 27 },
    { name: "Kontagora", state: 27 },
    { name: "Lapai", state: 27 },
    { name: "Lavun", state: 27 },
    { name: "Magama", state: 27 },
    { name: "Mariga", state: 27 },
    { name: "Mashegu", state: 27 },
    { name: "Mokwa", state: 27 },
    { name: "Moya", state: 27 },
    { name: "Paikoro", state: 27 },
    { name: "Rafi", state: 27 },
    { name: "Rijau", state: 27 },
    { name: "Shiroro", state: 27 },
    { name: "Suleja", state: 27 },
    { name: "Tafa", state: 27 },
    { name: "Wushishi", state: 27 },
    { name: "Abeokuta South", state: 28 },
    { name: "Ado-Odo-Ota", state: 28 },
    { name: "Egbado North", state: 28 },
    { name: "Egbado South", state: 28 },
    { name: "Ewekoro", state: 28 },
    { name: "Ifo", state: 28 },
    { name: "Ijebu East", state: 28 },
    { name: "Ijebu North", state: 28 },
    { name: "Ijebu North East", state: 28 },
    { name: "Ijebu Ode", state: 28 },
    { name: "Ikenne", state: 28 },
    { name: "Imeko Afon", state: 28 },
    { name: "Ipokia", state: 28 },
    { name: "Obafemi Owode", state: 28 },
    { name: "Odeda", state: 28 },
    { name: "Odogbolu", state: 28 },
    { name: "Ogun Waterside", state: 28 },
    { name: "Remo North", state: 28 },
    { name: "Shagamu", state: 28 },
    { name: "Akoko North-West", state: 29 },
    { name: "Akoko South-West", state: 29 },
    { name: "Akoko South-East", state: 29 },
    { name: "Akure North", state: 29 },
    { name: "Akure South", state: 29 },
    { name: "Ese Odo", state: 29 },
    { name: "Idanre", state: 29 },
    { name: "Ifedore", state: 29 },
    { name: "Ilaje", state: 29 },
    { name: "Ile Oluji-Okeigbo", state: 29 },
    { name: "Irele", state: 29 },
    { name: "Odigbo", state: 29 },
    { name: "Okitipupa", state: 29 },
    { name: "Ondo East", state: 29 },
    { name: "Ondo West", state: 29 },
    { name: "Ose", state: 29 },
    { name: "Owo", state: 29 },
    { name: "Atakunmosa West", state: 30 },
    { name: "Aiyedaade", state: 30 },
    { name: "Aiyedire", state: 30 },
    { name: "Boluwaduro", state: 30 },
    { name: "Boripe", state: 30 },
    { name: "Ede North", state: 30 },
    { name: "Ede South", state: 30 },
    { name: "Ife Central", state: 30 },
    { name: "Ife East", state: 30 },
    { name: "Ife North", state: 30 },
    { name: "Ife South", state: 30 },
    { name: "Egbedore", state: 30 },
    { name: "Ejigbo", state: 30 },
    { name: "Ifedayo", state: 30 },
    { name: "Ifelodun", state: 30 },
    { name: "Ila", state: 30 },
    { name: "Ilesa East", state: 30 },
    { name: "Ilesa West", state: 30 },
    { name: "Irepodun", state: 30 },
    { name: "Irewole", state: 30 },
    { name: "Isokan", state: 30 },
    { name: "Iwo", state: 30 },
    { name: "Obokun", state: 30 },
    { name: "Odo Otin", state: 30 },
    { name: "Ola Oluwa", state: 30 },
    { name: "Olorunda", state: 30 },
    { name: "Oriade", state: 30 },
    { name: "Orolu", state: 30 },
    { name: "Osogbo", state: 30 },
    { name: "Akinyele", state: 31 },
    { name: "Atiba", state: 31 },
    { name: "Atisbo", state: 31 },
    { name: "Egbeda", state: 31 },
    { name: "Ibadan North", state: 31 },
    { name: "Ibadan North-East", state: 31 },
    { name: "Ibadan North-West", state: 31 },
    { name: "Ibadan South-East", state: 31 },
    { name: "Ibadan South-West", state: 31 },
    { name: "Ibarapa Central", state: 31 },
    { name: "Ibarapa East", state: 31 },
    { name: "Ibarapa North", state: 31 },
    { name: "Ido", state: 31 },
    { name: "Irepo", state: 31 },
    { name: "Iseyin", state: 31 },
    { name: "Itesiwaju", state: 31 },
    { name: "Iwajowa", state: 31 },
    { name: "Kajola", state: 31 },
    { name: "Lagelu", state: 31 },
    { name: "Ogbomosho North", state: 31 },
    { name: "Ogbomosho South", state: 31 },
    { name: "Ogo Oluwa", state: 31 },
    { name: "Olorunsogo", state: 31 },
    { name: "Oluyole", state: 31 },
    { name: "Ona Ara", state: 31 },
    { name: "Orelope", state: 31 },
    { name: "Ori Ire", state: 31 },
    { name: "Oyo", state: 31 },
    { name: "Oyo East", state: 31 },
    { name: "Saki East", state: 31 },
    { name: "Saki West", state: 31 },
    { name: "Surulere", state: 31 },
    { name: "Barkin Ladi", state: 32 },
    { name: "Bassa", state: 32 },
    { name: "Jos East", state: 32 },
    { name: "Jos North", state: 32 },
    { name: "Jos South", state: 32 },
    { name: "Kanam", state: 32 },
    { name: "Kanke", state: 32 },
    { name: "Langtang South", state: 32 },
    { name: "Langtang North", state: 32 },
    { name: "Mangu", state: 32 },
    { name: "Mikang", state: 32 },
    { name: "Pankshin", state: 32 },
    { name: "Qua'an Pan", state: 32 },
    { name: "Riyom", state: 32 },
    { name: "Shendam", state: 32 },
    { name: "Wase", state: 32 },
    { name: "Ahoada East", state: 33 },
    { name: "Ahoada West", state: 33 },
    { name: "Akuku-Toru", state: 33 },
    { name: "Andoni", state: 33 },
    { name: "Asari-Toru", state: 33 },
    { name: "Bonny", state: 33 },
    { name: "Degema", state: 33 },
    { name: "Eleme", state: 33 },
    { name: "Emuoha", state: 33 },
    { name: "Etche", state: 33 },
    { name: "Gokana", state: 33 },
    { name: "Ikwerre", state: 33 },
    { name: "Khana", state: 33 },
    { name: "Obio-Akpor", state: 33 },
    { name: "Ogba-Egbema-Ndoni", state: 33 },
    { name: "Ogu-Bolo", state: 33 },
    { name: "Okrika", state: 33 },
    { name: "Omuma", state: 33 },
    { name: "Opobo-Nkoro", state: 33 },
    { name: "Oyigbo", state: 33 },
    { name: "Port Harcourt", state: 33 },
    { name: "Tai", state: 33 },
    { name: "Bodinga", state: 34 },
    { name: "Dange Shuni", state: 34 },
    { name: "Gada", state: 34 },
    { name: "Goronyo", state: 34 },
    { name: "Gudu", state: 34 },
    { name: "Gwadabawa", state: 34 },
    { name: "Illela", state: 34 },
    { name: "Isa", state: 34 },
    { name: "Kebbe", state: 34 },
    { name: "Kware", state: 34 },
    { name: "Rabah", state: 34 },
    { name: "Sabon Birni", state: 34 },
    { name: "Shagari", state: 34 },
    { name: "Silame", state: 34 },
    { name: "Sokoto North", state: 34 },
    { name: "Sokoto South", state: 34 },
    { name: "Tambuwal", state: 34 },
    { name: "Tangaza", state: 34 },
    { name: "Tureta", state: 34 },
    { name: "Wamako", state: 34 },
    { name: "Wurno", state: 34 },
    { name: "Yabo", state: 34 },
    { name: "Bali", state: 35 },
    { name: "Donga", state: 35 },
    { name: "Gashaka", state: 35 },
    { name: "Gassol", state: 35 },
    { name: "Ibi", state: 35 },
    { name: "Jalingo", state: 35 },
    { name: "Karim Lamido", state: 35 },
    { name: "Kumi", state: 35 },
    { name: "Lau", state: 35 },
    { name: "Sardauna", state: 35 },
    { name: "Takum", state: 35 },
    { name: "Ussa", state: 35 },
    { name: "Wukari", state: 35 },
    { name: "Yorro", state: 35 },
    { name: "Zing", state: 35 },
    { name: "Bursari", state: 36 },
    { name: "Damaturu", state: 36 },
    { name: "Fika", state: 36 },
    { name: "Fune", state: 36 },
    { name: "Geidam", state: 36 },
    { name: "Gujba", state: 36 },
    { name: "Gulani", state: 36 },
    { name: "Jakusko", state: 36 },
    { name: "Karasuwa", state: 36 },
    { name: "Machina", state: 36 },
    { name: "Nangere", state: 36 },
    { name: "Nguru", state: 36 },
    { name: "Potiskum", state: 36 },
    { name: "Tarmuwa", state: 36 },
    { name: "Yunusari", state: 36 },
    { name: "Yusufari", state: 36 },
    { name: "Bakura", state: 37 },
    { name: "Birnin Magaji-Kiyaw", state: 37 },
    { name: "Bukkuyum", state: 37 },
    { name: "Bungudu", state: 37 },
    { name: "Gummi", state: 37 },
    { name: "Gusau", state: 37 },
    { name: "Kaura Namoda", state: 37 },
    { name: "Maradun", state: 37 },
    { name: "Maru", state: 37 },
    { name: "Shinkafi", state: 37 },
    { name: "Talata Mafara", state: 37 },
    { name: "Chafe", state: 37 },
    { name: "Zurmi", state: 37 },
    { name: "Aboh Mbaise", state: 17 },
    { name: "Aninri", state: 14 },
    { name: "Aguata", state: 4 },
];

const stateBaseId = DATABASE.BASE_ID.STATE;
const staffBaseId = DATABASE.BASE_ID.STAFF;
const terminalBaseId = DATABASE.BASE_ID.TERMINAL;

const result = table.map((record, index) => {
    const obj = Object.assign({}, record);
    const id = index + 1;
    obj._id = toObjectId(terminalBaseId, id);
    obj.state = toObjectId(stateBaseId, record.state);
    obj.created_by = toObjectId(staffBaseId, "1");
    return obj;
});

export default result;
