import express from "express";

// Routes
import accountingRoute from "./accounting";
import admissionRoute from "./admission";
import assetAssignmentRoute from "./asset-assignment";
import assetRoute from "./asset";
import announcementRoute from "./announcement";
import attendanceRoute from "./attendance";
import bankAccountRoute from "./bank-account";
import bankRoute from "./bank";
import blogRoute from "./blog";
import bookRoute from "./book";
import budgetRoute from "./budget";
import calendarRoute from "./calendar";
import classeRoute from "./classe";
import classroomRoute from "./classroom";
import contactUsRoute from "./contact-us";
import countyRoute from "./county";
import documentTypeRoute from "./document-type";
import documentationRoute from "./documentation";
import feesRoute from "./fees";
import homeworkRoute from "./homework";
import hostelRoute from "./hostel";
import lessonRoute from "./lesson";
import multimediaRoute from "./multimedia";
import messageRoute from "./message";
import notificationRoute from "./notification";
import offenceRoute from "./offence";
import officeRoute from "./office";
import parentRoute from "./parent";
import payrollRoute from "./payroll";
import categoryRoute from "./category";
import marksheetRoute from "./marksheet";
import materialRoute from "./material";
import ratingRoute from "./rating";
import reportRoute from "./report";
import settingRoute from "./setting";
import setupRoute from "./setup";
import smsRoute from "./sms";
import staffRoute from "./staff";
import stageRoute from "./stage";
import stateRoute from "./state";
import studentRoute from "./student";
import subjectRoute from "./subject";
import synchronizationRoute from "./synchronization";
import tableRoute from "./table";
import taskRoute from "./task";
import timetableRoute from "./timetable";
import vehicleRoute from "./vehicle";
import voucherRoute from "./voucher";
import paystackRoute from "./paystack";
import unionbankRoute from "./unionbank";

const router = express.Router();

// Use Routes
router.use(accountingRoute);
router.use(admissionRoute);
router.use(assetAssignmentRoute);
router.use(assetRoute);
router.use(announcementRoute);
router.use(attendanceRoute);
router.use(bankAccountRoute);
router.use(admissionRoute);
router.use(bankRoute);
router.use(blogRoute);
router.use(bookRoute);
router.use(budgetRoute);
router.use(classeRoute);
router.use(classroomRoute);
router.use(calendarRoute);
router.use(contactUsRoute);
router.use(countyRoute);
router.use(feesRoute);
router.use(documentTypeRoute);
router.use(documentationRoute);
// router.use(homeworkRoute);
router.use(hostelRoute);
router.use(lessonRoute);
router.use(multimediaRoute);
router.use(messageRoute);
router.use(notificationRoute);
router.use(offenceRoute);
router.use(officeRoute);
router.use(parentRoute);
router.use(payrollRoute);
router.use(categoryRoute);
router.use(materialRoute);
router.use(marksheetRoute);
router.use(ratingRoute);
router.use(reportRoute);
router.use(settingRoute);
router.use(setupRoute);
router.use(smsRoute);
router.use(staffRoute);
router.use(stateRoute);
router.use(studentRoute);
router.use(subjectRoute);
router.use(synchronizationRoute);
router.use(tableRoute);
router.use(taskRoute);
router.use(timetableRoute);
router.use(vehicleRoute);
router.use(voucherRoute);
router.use(stageRoute);
router.use(paystackRoute);
router.use(unionbankRoute);

export default router;
