import express from "express";

// Routes
import accessRoute from "./access";
import accidentCauseRoute from "./accident-cause";
import accidentRoute from "./accident";
import accidentVictimRoute from "./accident-victim";
import accountClassRoute from "./account-class";
import accountHeadingRoute from "./account-heading";
import accountPostingRoute from "./account-posting";
import ancillaryRevenueRoute from "./ancillary-revenue";
import assetAssignmentRoute from "./asset-assignment";
import assetRoute from "./asset";
import attendanceRoute from "./attendance";
import bankAccountRoute from "./bank-account";
import bankRegisterRoute from "./bank-register";
import bankRoute from "./bank";
import bankTransactionRoute from "./bank-transaction";
import blogCommentRoute from "./blog-comment";
import blogRoute from "./blog";
import budgetRoute from "./budget";
import calendarRoute from "./calendar";
import cartRoute from "./cart";
import chatRoomRoute from "./chat-room";
import chatRoute from "./chat";
import cityRoute from "./city";
import contactUsRoute from "./contact-us";
import countryRoute from "./country";
import countyRoute from "./county";
import customerRoute from "./customer";
import crmRoute from "./crm";
import documentTypeRoute from "./document-type";
import documentationRoute from "./documentation";
import faultRoute from "./fault";
import hubRoute from "./hub";
import imageRoute from "./image";
import messageRoute from "./message";
import notificationRoute from "./notification";
import offenceRoute from "./offence";
import offenceTypeRoute from "./offence-type";
import officeRoute from "./office";
import partnerRoute from "./partner";
import payrollRoute from "./payroll";
import payrollDetailRoute from "./payroll-detail";
import productRoute from "./product";
import productionRoute from "./production";
import categoryRoute from "./category";
import maintenanceRoute from "./maintenance";
import materialRoute from "./material";
import purchaseOrderRoute from "./purchase-order";
import ratingRoute from "./rating";
import reportRoute from "./report";
import salesOrderRoute from "./sales-order";
import settingRoute from "./setting";
import setupRoute from "./setup";
import smsRoute from "./sms";
import staffRoute from "./staff";
import stageRoute from "./stage";
import stateRoute from "./state";
import stockRoute from "./stock";
import storeRoute from "./store";
import stockTransferRoute from "./stock-transfer";
import supplierRoute from "./supplier";
import synchronizationRoute from "./synchronization";
import tableRoute from "./table";
import taskRoute from "./task";
import teamRoute from "./team";
import terminalRoute from "./terminal";
import ticketRoute from "./ticket";
import vehicleRoute from "./vehicle";
import vehicleTrackingRoute from "./vehicle-tracking";
import voucherRoute from "./voucher";
import paystackRoute from "./paystack";
import unionbankRoute from "./unionbank";
import hostelRoute from "./hostel";

const router = express.Router();

// Use Routes
router.use(accessRoute);
router.use(accidentCauseRoute);
router.use(accidentRoute);
router.use(accidentVictimRoute);
router.use(accountClassRoute);
router.use(accountHeadingRoute);
router.use(accountPostingRoute);
router.use(ancillaryRevenueRoute);
router.use(assetAssignmentRoute);
router.use(assetRoute);
router.use(attendanceRoute);
router.use(bankAccountRoute);
router.use(bankRegisterRoute);
router.use(bankRoute);
router.use(bankTransactionRoute);
router.use(blogCommentRoute);
router.use(blogRoute);
router.use(budgetRoute);
router.use(calendarRoute);
router.use(cartRoute);
router.use(chatRoomRoute);
router.use(chatRoute);
router.use(cityRoute);
router.use(contactUsRoute);
router.use(countryRoute);
router.use(countyRoute);
router.use(customerRoute);
router.use(crmRoute);
router.use(documentTypeRoute);
router.use(documentationRoute);
router.use(faultRoute);
router.use(hubRoute);
router.use(imageRoute);
router.use(messageRoute);
router.use(notificationRoute);
router.use(offenceRoute);
router.use(offenceTypeRoute);
router.use(officeRoute);
router.use(payrollDetailRoute);
router.use(payrollRoute);
router.use(purchaseOrderRoute);
router.use(productRoute);
router.use(productionRoute);
router.use(categoryRoute);
router.use(materialRoute);
router.use(maintenanceRoute);
router.use(ratingRoute);
router.use(reportRoute);
router.use(salesOrderRoute);
router.use(settingRoute);
router.use(setupRoute);
router.use(smsRoute);
router.use(staffRoute);
router.use(stateRoute);
router.use(storeRoute);
router.use(stockTransferRoute);
router.use(stockRoute);
router.use(supplierRoute);
router.use(synchronizationRoute);
router.use(tableRoute);
router.use(taskRoute);
router.use(teamRoute);
router.use(terminalRoute);
router.use(ticketRoute);
router.use(partnerRoute);
router.use(vehicleRoute);
router.use(vehicleTrackingRoute);
router.use(voucherRoute);
router.use(stageRoute);
router.use(paystackRoute);
router.use(unionbankRoute);

export default router;
